config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  # LINE認証
  get "/auth/line/callback", to: "line_auth#callback"

  # Registrations
  resource :registrations, only: [ :new ] do
    collection do
      get "confirm"
      post "create"
      get "complete"
    end
  end

  # Users
  scope :users do
    get "/users/:id", to: "users#mypage", as: "users"
    # 開発用機能
    get "index", to: "users#index", as: "index"
    get "switch_user", to: "users#switch_user", as: "switch_user"
  end

  # Requests
  namespace :requests do
    get "confirm"
    get "remove"
    get "cancel"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :partner, class_name: "User"
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  enum status: { pending: "pending", accepted: "accepted", rejected: "rejected" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
    # 登録前の一時的なプロフィール画像のファイルパスを保持
    attr_accessor :tmp_profile_file_path, :tmp_profile_file, :application_for

    # 申請状態関係
    has_many :sent_requests, class_name: "Request", foreign_key: "sender_id", dependent: :destroy
    has_many :received_requests, class_name: "Request", foreign_key: "receiver_id", dependent: :destroy

    # 恋人関係
    has_one :relationship, foreign_key: "user_id", dependent: :destroy
    has_one :partner, through: :relationship, source: :partner

    # プロフィール画像
    has_one_attached :profile_image

    # ユーザーステータス
    # unset：恋人及び申請なし
    # pending：申請中
    # incoming：申請が来ている
    # registered：恋人登録済み
    enum status: { unset: "unset", pending: "pending", incoming: "incoming", registered: "registered" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # トップ画面表示用
  end
end

app/controllers/line_auth_controller.rb
class LineAuthController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :callback ]
  TMP_USER_IMAGE_PATH = "app/assets/images"

  def callback
    auth = request.env["omniauth.auth"]  # LINEからの認証情報を取得
    @user = User.find_or_initialize_by(uid: auth["uid"], provider: auth["provider"])
    @user.name = auth["info"]["name"]
    @user.line_user_id = auth["uid"]
    @user.provider = auth["provider"]
    @user.tmp_profile_file_path = image(auth, @user.line_user_id)
    redirect_to new_registrations_path(name: @user.name, line_user_id: @user.line_user_id, provider: @user.provider, tmp_profile_file_path: @user.tmp_profile_file_path)
  end

  def image(auth, line_user_id)
    # LINEから画像URLを取得して一時ファイルとして保存
    if auth["info"]["image"].present?
      begin
        image_file = URI.open(auth["info"]["image"]) # LINEの画像URLから取得
      rescue => e
        Rails.logger.error "プロフィール画像取得エラー: #{e.message}"
      end
    else
        # LINEから画像URLが取得できない場合はデフォルト画像を設定
        image_file = File.open(Rails.root.join("app/assets/images/default_profile.png"))
    end
    file_path = Rails.root.join(TMP_USER_IMAGE_PATH, "#{line_user_id}.jpg")
    File.open(file_path, "wb") { |f| f.write(image_file) }
    file_path
  end

  def failure
    Rails.logger.error "LINE認証エラー: #{e.message}"
    redirect_to root_path, alert: "LINE認証に失敗しました"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :check_login_user, except: :complete

  def new
    # 新規登録画面表示
    @user = User.new(name: params[:name], line_user_id: params[:line_user_id], provider: params[:provider], tmp_profile_file_path: params[:tmp_profile_file_path])
  end

  def confirm
    # 入力内容確認画面表示
    @user = User.new(name: params[:name], line_user_id: params[:line_user_id], provider: params[:provider], tmp_profile_file_path: params[:tmp_profile_file_path])
    @year = params[:year]
    @month = params[:month]
    @day = params[:day]
  end

  def create
    # 登録処理
    user = User.new(name: params[:name], line_user_id: params[:line_user_id], provider: params[:provider], tmp_profile_file_path: params[:tmp_profile_file_path])
    user.birthday = Date.new(Integer(params[:year]), Integer(params[:month]), Integer(params[:day]))
    begin
      if user.save
        sign_in(user)
        redirect_to complete_registrations_path(user_id: user.id),  notice: "Success to register"
      else
        redirect_to confirm_registrations_path, notice: "Failed to register"
      end
    rescue => e
      Rails.logger.error("Error saving user: #{e.message}")
      redirect_to confirm_registrations_path, notice: "Failed to register"
    end
  end

  def complete
    # 登録完了画面表示
    @user_id = current_user.id
  end

  private
  # 登録済みユーザーの場合はマイページに遷移する
  def check_login_user
    if User.exists?(line_user_id: params[:line_user_id])
      @user = User.find_by(line_user_id: params[:line_user_id])
      sign_in(@user)
      redirect_to users_path(@user)
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def confirm
    # 恋人申請確認画面表示
  end

  def remove
    # 恋人登録解除確認画面表示
  end

  def cancel
    # 恋人申請取り消し画面表示
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  # Userビューのルーティング。
  # UserのStatus応じたビューにリダイレクトする
  def route
    case @user.status
    when "unset"
      redirect_to users_unset_path
    when "pending"
      redirect_to users_pending_path
    when "incoming"
      redirect_to users_incoming_path
    when "registered"
      redirect_to users_registered_path
    end
  end

  def unset
    # マイページ（未登録）表示
  end

  def pending
    # マイページ（未登録）表示
  end

  def incoming
    # マイページ（申請が来ている）表示
  end

  def registered
    # マイページ（登録済み）表示
  end

  # 開発用機能
  def index
    @users = User.all
    # 恋人申請中の場合は申請相手を取得する
    @users.each do |user|
      if user.status === pending
        # 恋人申請中の場合
        user.application_for = "pending:#{user.partner}"
      end
      if user.status === incoming
        # 恋人申請中の場合
        user.application_for = "pending:#{user.partner}"
      end
    end
  end

  def switch_user
    sign_in(User.find(params[:id]))
    redirect_to users_path
  end

  private
  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_auth_helper.rb
module LineAuthHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">
    <h1>Home#index</h1>
    <p>Find me in app/views/home/index.html.erb</p>
    <%= link_to "LINEでログイン", "/auth/line/" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "First Line App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/requests/cancel.html.erb
<h1>Requests#cancel</h1>
<p>Find me in app/views/requests/cancel.html.erb</p>

app/views/requests/confirm.html.erb
<h1>Requests#confirm</h1>
<p>Find me in app/views/requests/confirm.html.erb</p>

app/views/requests/remove.html.erb
<h1>Requests#remove</h1>
<p>Find me in app/views/requests/remove.html.erb</p>

app/views/users/_incoming.html.erb
<h1>incoming</h1>

app/views/users/_pending.html.erb
<h1>pending</h1>

app/views/users/_registered.html.erb
<h1>registered</h1>

app/views/users/_unset.html.erb
<h1>unset</h1>

app/views/users/index.html.erb
<h1>ユーザー切り替え</h1>

<table>
  <thead>
    <tr>
      <th hidden>LINEユーザーID (隠し項目)</th>
      <th>名前</th>
      <th>ステータス</th>
      <th>申請相手</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td hidden><%= user.line_user_id %></td>
        <td><%= user.name %></td>
        <td><%= user.status %></td>
        <td><%= user.application_for %></td>
        <td>
          <%= button_to '切り替え', switch_user_path(user), method: :post %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/mypage.html.erb
<div class="container">ログインユーザーは<%= @user.name %>です</div>
<div>
    <%= render "#{current_user.status}" %>
</div>